[sources.demo]
type = "demo_logs"
format = "apache_common"

[sinks.loki]
type = "loki"
inputs = ["demo"]
endpoint = "<GRAFANA_CLOUD_URL>"
out_of_order_action = "accept"
compression = "snappy"
encoding.codec = "json"
auth.strategy = "basic"
auth.user = "<GRAFANA_CLOUD_USER_ID>"
auth.password = "<GRAFANA_CLOUD_TOKEN>"
