# fly.toml app configuration file generated for rogue-scholar-cache on 2024-12-03T13:38:21+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rogue-scholar-cache'
primary_region = 'fra'

[build]
  image = 'valkey/valkey:7.2.5-bookworm'

[[mounts]]
  source = 'redis_server'
  destination = '/data'

[http_service]
  internal_port = 6379
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2

[[metrics]]
  port = 9091
  path = '/metrics'
  https = false
