# fly.toml app configuration file generated for rogue-scholar-caddy on 2024-11-03T11:26:41+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rogue-scholar-caddy'
primary_region = 'fra'

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services.ports]]
  handlers = ["http"]
  port = 80
  # force_https = true

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "caddy_data"
  destination = "/data"
