---
title: Guidelines
---

These guidelines are recommendations for authors of scholarly blogs to help with long-term archiving, discoverability, and citation of the blog content.
They are modelled after the publication *A Data Citation Roadmap for Scholarly Data Repositories* (1), where many of the same guidelines apply, and where the first author is also involved in the Rogue Scholar. Background info about these guidelines is in a blog post (2).

These guidelines focus on the required or recommended work for scholarly blog authors. For scholarly blog archives additional guidelines are in development.

| Level       | #  | Guideline                     |
| ----------- | -: | ----------------------------- | 
| Required    | 1  | The full-text content *must* be made available via public RSS feed (in RSS, Atom or JSON Feed format). |
| Required    | 2  | Each blog post in the RSS feed *must* have a title, author(s), and publication date. |
| Required    | 3  | Each blog post *must* have a URL that resolves to a public landing page specific for that blog post. |
| Required    | 4  | The full-text content *must* be made available via a Creative Commons Attribution (CC-BY) license. |
| Recommended | 5  | The blog must provide documentation about long-term archiving, discoverability, and citation. |
| Recommended | 6  | Each blog post in the RSS feed *should* have a persistent identifier, description, language, and last updated date. |
| Recommended | 7  | The landing page *should* include metadata required for citation, and ideally also metadata facilitating discovery, in human-readable and machine-readable format. |
| Recommended | 8  | The machine-readable metadata *should* use schema.org markup in JSON-LD format. |
| Recommended | 9  | Metadata *should* be made available via HTML meta tags to facilitate use by reference managers. |
| Recommended | 10 | Metadata *should* be made available for download in BibTeX and/or another standard bibliographic format. |

### References

1. Fenner, M., Crosas, M., Grethe, J. S., Kennedy, D., Hermjakob, H., Rocca-Serra, P., Durand, G., Berjon, R., Karcher, S., Martone, M., &amp; Clark, T. (2019). A data citation roadmap for scholarly data repositories. <i>Scientific Data</i>, <i>6</i>(1). <a href="https://doi.org/10.1038/s41597-019-0031-8">https://doi.org/10.1038/s41597-019-0031-8</a>
1. Fenner, M. (2023). Guidelines for Scholarly Blogs. <i>Front Matter</i>. <a href="https://doi.org/10.53731/a0d9m3n-n7r8h0m">https://doi.org/10.53731/a0d9m3n-n7r8h0m</a>
