---
title: Overview
---

The following blogging platforms are used by Rogue Scholar blogs:

- [Wordpress](https://wordpress.org/)
- [Ghost](https://ghost.org/)
- [Hugo](https://gohugo.io/)
- [Jekyll](https://jekyllrb.com/)
- [Blogger](https://blogger.com)
- [Quarto](https://quarto.org)
- [Substack](https://substack.com)
- [Medium](https://medium.com)

Blogger, Substack and Medium are hosted services using proprietary software. 
The other platforms are available as open source software that you can either be install yourself,
or pay for the convenience of a hosted version.

## Content Management Systems (CMS)

Wordpress and Ghost are Content Management Systems that are specialized for generating blogs.
Wordpress in particular can also be used for other use cases and powers more than [40% of all
websites](https://w3techs.com/). Traditional Content Management Systems (such as Wordpress and Ghost)
use a database backend. More generic Content Management Systems such as Drupal or Joomla are
sometimes also used for blogs, in particular if the site also generates our types of content.

<Callout type="info" emoji="💡">
  CMS-based blogs come with a monthly cost of typically $10 - $20. They require little or no technical knowledge. 
  They are less flexible than static site generators.
</Callout>

## Static Site Generators

Hugo, Jekyll and Quarto are static site generators that turn your blog posts (or any other content) written in Markdown
format into an HTML website that can be hosted easily. [Hugo Blox](https://hugoblox.com) (formerly 
Wowchemy Hugo Modules) is an all-in-one web framework for easily building any kind of website with blocks (no-code), based on Hugo.
Quarto is an open-source scientific and technical publishing system.

[GitHub Pages](https://pages.github.com/) is one popular option that lets GitHub host your blog. GitHub Pages 
have a special integration with Jekyll, but work with all static site generators, including Hugo and Quarto. 
Other popular options to host blogs generated by static site generators include [Vercel](https://vercel.com) 
and [Netlify](https://netlify.com).

Static site generators can also use a Headless Content Management System, which use a database, backend API, and admin user interface,
but leave the user-facing frontend for the static site generator. Dynamic content such as search or comments can be
generated with Javascript, and the term [JAMStack](https://jamstack.org/) (Javascript, API and Markup) has been coined
in 2015 to describe this architecture.

<Callout type="info" emoji="💡">
  Static site generators are free to use or come with a low monthy cost. They require more technical knowledge than CMS-based systems,
  including a basic understanding of markdown and YAML metadata.
</Callout>

## RSS, Atom, JSON Feeds and APIs

All blogging platforms produce RSS feeds of the content they publish, making it easy to read content
with an RSS reader, and for other systems to read the content and metadata in an automated way.
RSS and the related Atom have been around for about 20 years, use XML as a serialization format, and libraries to
read and generate content exist in all programming languages. For science blogs RSS has two important
limitations: it doesn't support multiple authors or additional author metadata, and it doesn't support `date_updated`.
Atom overcomes these limitations and is therefore the preferred feed format. The much newer [JSON Feed](https://www.jsonfeed.org/) uses
JSON instead of XML for serialization, which is much easier to read and write. Several blogging platforms support multiple feed
formats out of the box or via plugins or themes.

An alternative to RSS, Atom or JSON Feeds is an API to read content. This is not possible for static site
generators because of the way they work, but supported by several blogging platforms using database backends. The Ghost API requires
authentication, and the official Medium API was discontinued in March 2023. All APIs use JSON.

RSS feeds focus on recent content whereas APIs give access to all content, using pagination. Wordpress and Blogger support pagination
in their RSS/Atom feeds.

| Platform  | Type   | RSS   | Atom   | JSON Feed | API   |
| :-------- | :----- | :---- | :----- | :-------- | :---- |
| Wordpress | CMS    | yes   | yes    | plugin    | yes   |
| Ghost     | CMS    | yes   | theme  | theme     | yes   |
| Hugo      | static | yes   | theme  | theme     | no    |
| Jekyll    | static | no    | plugin | plugin    | no    |
| Blogger   | CMS    | yes   | yes    | no        | no    |
| Quarto    | static | yes   | no     | no        | no    |
| Substack  | CMS    | yes   | no     | no        | yes   |
| Medium    | CMS    | yes   | no     | no        | no    |

## Recommendations

Rogue Scholar works with all blogging platforms, so it is really up to the user or organization to pick a blogging platform, and there
is no need to switch to a particular platform before joining Rogue Scholar. Nevertheless, we can give the following general recommendations:

* If you are happy with your blogging platform, continue using it.
* Use an open source platform. With commercial platforms you run the risk of the platform significantly changing prices, policies, or even shutting down.
* Decide whether you prefer a CMS or static site generator. There are good arguments for both (see above).
* Use a platform that has an API or supports Atom feeds.

There is currently no standard export format for blogs, but some platforms have importers to import content and metadata
from other platforms.
