name: Update DOIs for changed Posts
on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"
env:
  UV_SYSTEM_PYTHON: 1
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download records not registered with Crossref
        run: |
          mkdir -p upload
          curl https://rogue-scholar.org/api/records?q=custom_fields.rs%5C%3Astale%3Atrue&l=list&s=10&sort=newest | jq '.hits.hits' > upload/inveniordm.json
      - name: Validate JSON file
        run: |
          if ! jq empty upload/inveniordm.json; then
            echo "Error: Downloaded JSON is not valid"
            exit 1
          fi
      - name: Set number of records to be registered as variable
        id: current_number
        run: |
          echo "NUMBER=$(jq 'length' upload/inveniordm.json)" >> $GITHUB_OUTPUT
      - name: Install uv
        if: ${{ fromJSON(steps.current_number.outputs.NUMBER) > 0 }}
        uses: astral-sh/setup-uv@v5
      - name: "Set up Python"
        if: ${{ fromJSON(steps.current_number.outputs.NUMBER) > 0 }}
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install commonmeta-py
        if: ${{ fromJSON(steps.current_number.outputs.NUMBER) > 0 }}
        run: |
          uv pip install 'commonmeta-py>=0.153'
      - name: Set current date as variable
        if: ${{ fromJSON(steps.current_number.outputs.NUMBER) > 0 }}
        run: |
          echo "NOW=$(date +'%s')" >> $GITHUB_OUTPUT
        id: current_date
      - name: Upsert Crossref DOIs
        if: ${{ fromJSON(steps.current_number.outputs.NUMBER) > 0 }}
        run: |
          uv run commonmeta push upload/inveniordm.json -f inveniordm -t crossref_xml --depositor "${{ secrets.CROSSREF_DEPOSITOR_NAME }}" --email "${{ secrets.CROSSREF_DEPOSITOR_EMAIL }}" --registrant "${{ secrets.CROSSREF_REGISTRANT }}" --login_id "${{ secrets.CROSSREF_USERNAME_WITH_ROLE }}" --login_passwd "${{ secrets.CROSSREF_PASSWORD }}" --host rogue-scholar.org --token "${{ secrets.INVENIORDM_TOKEN }}" --legacy-key "${{ secrets.SUPABASE_KEY }}" > upload/response.json
          cat upload/response.json
