name: Update DOIs for changed Posts
on:
  workflow_dispatch:
  schedule:
   - cron: "*/10 * * * *"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4       
      - name: setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23'
      - name: Download posts not indexed recently
        run: |
          mkdir -p upload
          curl https://api.rogue-scholar.org/posts/updated?per_page=1 > upload/posts.json
      - name: Set number of posts to be updated as variable
        id: current_number
        run: |
          echo "NUMBER=$(jq '."total-results"' upload/posts.json)" >> $GITHUB_OUTPUT
      - name: Install commonmeta
        if: ${{ fromJSON(steps.current_number.outputs.NUMBER) > 0 }} 
        run: |
          go install github.com/front-matter/commonmeta@v0.5.30
          commonmeta version
      - name: Set current date as variable
        if: ${{ fromJSON(steps.current_number.outputs.NUMBER) > 0 }} 
        run: |
          echo "NOW=$(date +'%s')" >> $GITHUB_OUTPUT
        id: current_date
      - name: Convert posts to commonmeta
        if: ${{ fromJSON(steps.current_number.outputs.NUMBER) > 0 }}
        run: |
          commonmeta list upload/posts.json -f jsonfeed > upload/commonmeta.json
      - name: Update Crossref DOIs
        if: ${{ fromJSON(steps.current_number.outputs.NUMBER) > 0 }}
        run: |
          commonmeta push upload/commonmeta.json -f commonmeta -t crossrefxml --depositor "${{ secrets.CROSSREF_DEPOSITOR_NAME }}" --email "${{ secrets.CROSSREF_DEPOSITOR_EMAIL }}" --registrant "${{ secrets.CROSSREF_REGISTRANT }}" --login_id "${{ secrets.CROSSREF_USERNAME_WITH_ROLE }}" --login_passwd "${{ secrets.CROSSREF_PASSWORD }}" > upload/response.json
      - name: update InvenioRDM content
        if: ${{ fromJSON(steps.current_number.outputs.NUMBER) > 0 }}
        run: |
          commonmeta push upload/commonmeta.json -f commonmeta -t inveniordm --host rogue-scholar.org --token ${{ secrets.INVENIORDM_TOKEN }} > upload/response.json
          echo "UUIDS=$(jq -rc '[.[] | .uuid] | join(",")' upload/response.json)" >> $GITHUB_OUTPUT
        id: response
      - name: Update Rogue Scholar posts
        if: ${{ fromJSON(steps.current_number.outputs.NUMBER) > 0 }}
        run: |
          curl -X PATCH https://db.rogue-scholar.org/rest/v1/posts?id=in.%28${{ steps.response.outputs.UUIDS }}%29 -H "apikey: ${{ secrets.SUPABASE_KEY }}" -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}" -H "Content-Type: application/json" -H "Prefer: return=minimal" -d '{ "indexed_at": "${{ steps.current_date.outputs.NOW }}", "indexed": true }'
